version: "3.8"
services:

  prefect-server:
    image: prefecthq/prefect:3-latest
    command:  prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    environment:
      PREFECT_LOGGING_LEVEL: INFO
      PREFECT_SERVER_API_AUTH_STRING: "admin:pass"
      # PREFECT_SERVER_API_HOST: 0.0.0.0

    volumes:
      - prefect_data:/root/.prefect

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prefect-pipe
    restart: unless-stopped
    ports:
      - "5438:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    container_name: prefect-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


volumes:
  postgres_data:
  minio_data:
  prefect_data:
