[project]
name = "prefect-etl-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "prefect[aws,sqlalchemy]>=3.4.25",
    "psycopg2-binary==2.9.11",
    "s3fs>=2025.10.0",
]
